# Generated by Django 3.2 on 2021-09-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.FileField(upload_to='upload_txt', verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='WordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('tf', models.FloatField(blank=True, null=True)),
                ('idf', models.FloatField(blank=True, null=True)),
                ('int_word', models.IntegerField()),
                ('texts', models.ManyToManyField(to='viewdowapp.FormDownload')),
            ],
        ),
    ]
